using Core.Helpers;
using Core.IIIF;
using IIIF;
using IIIF.Presentation.V3;
using IIIF.Presentation.V3.Strings;
using IIIF.Search.V2;
using Microsoft.Extensions.Logging;
using Services.Manifests;
using DbManifest = Models.Database.Collections.Manifest;

namespace Services.TextServices;

/// <summary>
/// Augments a manifest with text-services content - retrieving the text-augmented manifest from text-services and
/// merging any <see cref="SearchService2"/>, rendering (e.g. PDF) and annotations (e.g. manifest-level "all-text"
/// and per-canvas line/word transcriptions from METS/ALTO) into the manifest.
/// </summary>
public interface ITextManifestAugmentor : IManifestAugmentor
{
}

public class TextManifestAugmentor(ITextSearchClient textSearchClient, ILogger<TextManifestAugmentor> logger)
    : ITextManifestAugmentor
{
    public async Task<Manifest> Augment(Manifest manifest, DbManifest dbManifest, CancellationToken cancellationToken)
    {
        // The job id is deterministic from the manifest - see PipelineJobX.GetJobId
        var jobId = new TextJobId(dbManifest.CustomerId, dbManifest.Id);

        var augmented = await textSearchClient.GetTextAugmentedManifest(jobId, cancellationToken);
        if (augmented == null)
        {
            logger.LogDebug("No text-augmented manifest found for job {JobId}", jobId);
            return manifest;
        }

        AddSearchServices(manifest, augmented, jobId);
        AddRendering(manifest, augmented, jobId);
        AddManifestAnnotations(manifest, augmented, jobId);
        AddCanvasAnnotations(manifest, augmented, jobId);

        return manifest;
    }

    private void AddSearchServices(Manifest manifest, Manifest augmented, TextJobId jobId)
    {
        var searchServices = augmented.Service?.OfType<SearchService2>().ToList();
        if (searchServices.IsNullOrEmpty())
        {
            logger.LogDebug("No SearchService2 in text-augmented manifest for job {JobId}", jobId);
            return;
        }

        // Add search service to manifest, if added then ensure Manifest has the search context
        manifest.Service ??= [];
        var added = manifest.Service.AddDistinctById(searchServices, AddService);
        if (added > 0)
        {
            manifest.EnsureContext(SearchService2.Search2Context);
            logger.LogDebug("Added SearchService2 to manifest for job {JobId}", jobId);
        }
        else
        {
            logger.LogDebug("Found SearchService2 but did not augment manifest for job {JobId}", jobId);
        }
    }

    /// <summary>
    /// Add any PDF renderings generated by text-services (e.g. a searchable PDF) to the manifest.
    /// </summary>
    private void AddRendering(Manifest manifest, Manifest augmented, TextJobId jobId)
    {
        if (augmented.Rendering.IsNullOrEmpty())
        {
            logger.LogDebug("No rendering in text-augmented manifest for job {JobId}", jobId);
            return;
        }

        manifest.Rendering ??= [];
        var added = manifest.Rendering.AddDistinctById(augmented.Rendering);
        logger.LogDebug("Added {Count} rendering to manifest for job {JobId}", added, jobId);
    }

    /// <summary>
    /// Add any manifest-level W3C annotations generated by text-services (e.g. the "all-text" page, figures) to
    /// the manifest.
    /// </summary>
    private void AddManifestAnnotations(Manifest manifest, Manifest augmented, TextJobId jobId)
    {
        if (augmented.Annotations.IsNullOrEmpty())
        {
            logger.LogDebug("No manifest-level annotations in text-augmented manifest for job {JobId}", jobId);
            return;
        }

        manifest.Annotations ??= [];
        var added = manifest.Annotations.AddDistinctById(augmented.Annotations);
        logger.LogDebug("Added {Count} manifest-level annotations to manifest for job {JobId}", added, jobId);
    }

    /// <summary>
    /// Add any canvas-level W3C annotations generated by text-services (e.g. line/word transcriptions from
    /// METS/ALTO) to the matching canvas, matched by canvas id.
    /// </summary>
    private void AddCanvasAnnotations(Manifest manifest, Manifest augmented, TextJobId jobId)
    {
        if (manifest.Items.IsNullOrEmpty() || augmented.Items.IsNullOrEmpty())
        {
            logger.LogDebug("No canvases to add canvas-level annotations to for job {JobId}", jobId);
            return;
        }

        var augmentedCanvasesById = augmented.Items
            .Where(c => c.Id != null)
            .ToDictionary(c => c.Id!);

        var canvasesUpdated = 0;
        foreach (var canvas in manifest.Items)
        {
            if (canvas.Id == null || !augmentedCanvasesById.TryGetValue(canvas.Id, out var augmentedCanvas))
                continue;
            if (augmentedCanvas.Annotations.IsNullOrEmpty()) continue;

            canvas.Annotations ??= [];
            if (canvas.Annotations.AddDistinctById(augmentedCanvas.Annotations) > 0) canvasesUpdated++;
        }

        logger.LogDebug("Added canvas-level annotations to {Count} canvases for job {JobId}", canvasesUpdated,
            jobId);
    }

    private static void AddService(IService service)
    {
        // Expectation is we'll get a SearchService2 containing an AutoCompleteService2. Set labels on these if null
        if (service is SearchService2 searchService)
        {
            searchService.Label ??= new LanguageMap("en", "Search within this manifest");
            // We're only expecting 1 here but use FirstOrDefault, rather than SingleOrDefault to avoid throwing if
            // text-service adds unexpected service.
            var autoComplete = searchService.Service?.OfType<AutoCompleteService2>().FirstOrDefault();
            if (autoComplete != null)
            {
                autoComplete.Label ??= new LanguageMap("en", "Autocomplete words in this manifest");
            }
        }
    }
}
