name: Run Automated Tests
on:
  push:
    branches: [ "main", "develop" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore:
      - "docs/**"
      - "scripts/**"

jobs:
  test-playwright:
    runs-on: ubuntu-latest
    needs: test-dotnet
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_TESTS_PRIVATE_KEY }}
          repository: dlcs/iiif-presentation-tests